# Example Config File
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "lcerritos-cs"
    default_labels:
      - "CETeam"
    ignored_updates:
      - match:
          dependency_name: "spring*"

